### ISSUE TITLE
Some files aren't included

### ISSUE THREAD

**Issue by XTHESilent** [Devedeu/Dotfiles#1]
So,  most of the files are in the .cache folder, i applied the hyprland.conf file but line 4 was "source = ~/.cache/wal/colorsHyprland.conf" which doesnt exist on this repo, and the vesktop theme only contains "/home/portocala2/.cache/wal/colors-discord.css" and there is no installations instructions, you didnt specify what packages to install, or anything, so i literally cant install it.
pls fix it ;-;

**Comment by Devedeu** [comment]
This is because wal doesn't have a template from which to create the files in .cache. You can fix this by going into .config/wal/templates, taking whatever files you need from there, and putting them into your .config/wal/templates

For vesktop, the theme is from here https://github.com/ZephyrCodesStuff/pywal-vencord and it has everything you need

**Comment by XTHESilent** [comment]
tysm :D, btw i have a questions, can you list all the packages that needs to be installed?

**Comment by Devedeu** [comment]
none of the configs should require any specific packages, just some searching to see what isn't working in the configs. A lot of things specify errors if you start them in a terminal, like waybar
